### ISSUE TITLE
安装错误,源挂了

### ISSUE THREAD

**Issue by cbin000** [AiCorein/arch-wine-neteasemusic#1]
curl: (22) The requested URL returned error: 404
==> 错误： 无法下载 https://mirrors.sdu.edu.cn/spark-store-repository/store/music/com.163.music.spark/com.163.music.spark_3.0.1.201795spark10_amd64.deb
    正在放弃...
 -> 下载源文件时出错: /home/cbin/.cache/yay/com.163.music.spark 
         context: exit status 1

**Comment by aicorein** [comment]
今早我也发现上游源更新了。我计划本来是今下午同步更新一下这个项目。但没想到你正好这个时候准备安装。
你现在急的话可以先到 https://mirrors.sdu.edu.cn/spark-store-repository/store/music/com.163.music.spark/ 下载最新的 deb 文件。然后更改 PKGBUILD 里的 source 变量为本地 deb 路径，再 `makepkg -si` 安装就行了。
不急的话就再等会儿，一会儿我有空就来处理这个事儿。

**Comment by cbin000** [comment]
好的,谢谢

**Comment by aicorein** [comment]
aur 仓库和 github 仓库已同步上游更改。
