### ISSUE TITLE
源文件不可访问

### ISSUE THREAD

**Issue by felixtensor** [AiCorein/arch-wine-neteasemusic#4]
新版本的上线了，旧版本的源文件已不能访问到了。
新版本地址：https://mirrors.sdu.edu.cn/spark-store-repository/store/music/com.163.music.spark/com.163.music.spark_3.0.1.202031spark12.1_amd64.deb

**Comment by aicorein** [comment]
软件包已同步 3.0.1.202031spark12.1 版本
